import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';

await fs.mkdir('test-results', { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', headless: true, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
page.setDefaultTimeout(20000);
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const base = process.env.GAME_URL || 'http://127.0.0.1:5173';
const offlinePlay = process.env.OFFLINE_PLAY === '1';
const state = () => page.evaluate(() => window.__garden.snapshot());
const plot = async (index) => {
  const p = await page.evaluate(i => window.__garden.screenPoint(560 + i % 4 * 86 + 40, 448 + Math.floor(i / 4) * 78 + 40), index);
  await page.mouse.click(p.x, p.y);
};
try {
  await page.goto(base);
  if (offlinePlay) await page.context().setOffline(true);
  await page.getByRole('button', { name: /เข้าสวนกันเลย/ }).click();
  await page.waitForFunction(() => window.__garden && document.querySelector('canvas'));
  await page.waitForTimeout(500);
  await page.screenshot({ path: 'test-results/desktop-start.png' });
  await plot(0);
  await page.waitForFunction(() => window.__garden.snapshot().harvested === 1);
  assert.equal((await state()).basket.carrot, 1);

  await page.getByRole('button', { name: 'พรวนดิน', exact: true }).click(); await plot(8);
  await page.waitForFunction(() => window.__garden.snapshot().plots[8].tilled);
  await page.getByRole('button', { name: 'ปลูกเมล็ด', exact: true }).click(); await plot(8);
  await page.waitForFunction(() => window.__garden.snapshot().plots[8].crop === 'carrot');
  assert.equal((await state()).seeds.carrot, 5);
  await page.getByRole('button', { name: 'รดน้ำ', exact: true }).click(); await plot(8);
  await page.waitForFunction(() => window.__garden.snapshot().plots[8].wateredAt !== null);
  const beforeSleep = await state();
  await page.locator('#rest').click();
  const pausedAt = (await state()).time;
  await page.waitForTimeout(300);
  assert.equal((await state()).time, pausedAt, 'modal pauses the simulation');
  await page.getByRole('button', { name: /พักจนถึงเช้า/ }).click();
  assert.equal((await state()).day, beforeSleep.day + 1);
  assert.equal((await state()).energy, 100);
  await page.getByRole('button', { name: 'เก็บเกี่ยว', exact: true }).click(); await plot(8);
  await page.waitForFunction(() => window.__garden.snapshot().harvested === 2);
  await page.locator('#basket').click();
  await page.getByRole('button', { name: /ขายผลผลิตทั้งหมด/ }).click();
  assert.equal((await state()).coins, 108);
  assert.equal((await state()).basket.carrot, 0);
  await page.locator('#close-modal').click();
  await page.locator('#shop').click();
  await page.locator('[data-buy="strawberry"]').click();
  assert.equal((await state()).coins, 98);
  assert.equal((await state()).seeds.strawberry, 3);
  await page.screenshot({ path: 'test-results/desktop-shop.png' });
  await page.locator('#close-modal').click();

  await page.keyboard.press('2');
  await page.locator('[data-crop="strawberry"]').click(); await plot(8);
  await page.waitForFunction(() => window.__garden.snapshot().plots[8].crop === 'strawberry');
  await page.keyboard.press('3'); await plot(8);
  await page.waitForFunction(() => window.__garden.snapshot().plots[8].wateredAt !== null);
  await page.locator('#rest').click(); await page.locator('#sleep').click();
  await page.keyboard.press('4'); await plot(8);
  await page.waitForFunction(() => window.__garden.snapshot().questDone);
  assert.equal((await state()).coins, 128);
  const saved = await state();
  if (offlinePlay) await page.context().setOffline(false);
  await page.reload();
  if (offlinePlay) await page.context().setOffline(true);
  await page.waitForFunction(() => window.__garden && document.querySelector('canvas'));
  await page.waitForTimeout(500);
  const restored = await state();
  assert.equal(restored.coins, saved.coins);
  assert.equal(restored.day, saved.day);
  assert.deepEqual(restored.basket, saved.basket);
  assert.equal(await page.locator('#modal').isVisible(), false);
  const startX = restored.player.x;
  await page.keyboard.down('d');
  await page.waitForFunction(x => window.__garden.snapshot().player.x > x + 20, startX);
  await page.keyboard.up('d');
  assert.ok((await state()).player.x > startX + 20, 'keyboard movement works');
  await page.screenshot({ path: 'test-results/desktop-play.png' });

  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  mobile.setDefaultTimeout(20000);
  mobile.on('pageerror', e => errors.push(e.message));
  await mobile.goto(base);
  if (offlinePlay) await mobile.context().setOffline(true);
  await mobile.getByRole('button', { name: /เข้าสวนกันเลย/ }).tap();
  await mobile.waitForTimeout(900);
  await mobile.screenshot({ path: 'test-results/mobile-play.png' });
  const mp = await mobile.evaluate(() => window.__garden.screenPoint(600, 488));
  await mobile.touchscreen.tap(mp.x, mp.y);
  await mobile.waitForFunction(() => window.__garden.snapshot().harvested === 1);
  await mobile.locator('#shop').tap();
  await mobile.screenshot({ path: 'test-results/mobile-shop.png' });
  assert.ok(await mobile.locator('[data-buy="carrot"]').isVisible());
  await mobile.locator('#close-modal').tap();
  const bounds = await mobile.locator('.toolbar').boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390, 'mobile toolbar fits');
  assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, [], 'no browser runtime errors');
  console.log('PASS: desktop crop loop, trading, quest, save/reload, keyboard movement, modal pause, mobile touch harvest and responsive HUD.');
} finally { await browser.close(); }
